[package]
name = "vec_diff"
version = "0.1.0"
authors = ["AndrewSC208 <meilingandrew@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
